### PR TITLE
Modularization modeling and data pipeline

### PR DESCRIPTION
**Pull request by 786213750**

### CODE REVIEW

**Comment by 786213750** [comment]
This PR is ready for review.

**Comment by AReyH** [comment]
@786213750 Can you change the name of the folder to "test" to match @ianm99 and @sifanzzz ?

**Review by sifanzzz — COMMENTED** [review]
well done

**Review by ianm99 — APPROVED** [review]
This looks good!

**Comment by 786213750** [comment]
> @786213750 Can you change the name of the folder to "test" to match @ianm99 and @sifanzzz ?

yea, done.

**Pull request merged**
